services:
  - type: web
    name: knowledge-base
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py loaddata datadump.json
    startCommand: gunicorn bz_project.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DATABASE_URL
        value: postgresql://base_user:7V29YI03tZC6jK47nQOeXlBiWPmnwgyv@dpg-d8ufa4tckfvc73f4hkvg-a/base_db_vqgs